winston/views/ChangeAuthAPIKey.swift
winston/views/Onboarding/Steps/OnboardingAPIIntro.swift

The API ratelimit is 100 requests per minute as of 2 months ago.
Source: https://support.reddithelp.com/hc/en-us/articles/16160319875092-Reddit-Data-API-Wiki

60 to 100 ratelimit

---

TestFlight/WhatToTest.en-US.txt
winston/Tabber.swift
winston/components/Badge.swift
winston/components/ImageMediaPost.swift
winston/components/Links/CommentLink/CommentLinkContent.swift
winston/components/Links/ShortCommentPostLink.swift
winston/globals/defaults.swift
winston/models/Comment.swift
winston/models/RedditAPI/subs/fetchSubPosts.swift
winston/models/RedditAPI/subs/fetchSubs.swift
winston/models/Subreddit.swift
winston/views/PostView/PostView.swift
winston/views/Settings/views/AppearancePanel.swift
winston/views/Subreddits/Subreddits.swift

- Add some missing icons for comment sort and post sort
- Renamed Notifications to Inbox for more consistency
- Added a toggle to disable username colouring
- Made the OP username color in the post also green to be in line with the comment OP color

UI Improvements

---

winston/globals/defaults.swift
winston/views/Settings/views/BehaviorPanel.swift
winston/views/Subreddits/Subreddits.swift

- Adds support for selecting a default feed for the app to open to

Default feed option

---

winston/modifiers/loader.swift
winston/views/Search.swift

- Adds support for debounced search, will search as a user types if they dont change the query within .25 seconds
- Adds indicator if no results are returned
- Sorts subreddit results by amount of subscribers

Add debounced search while users type

---

winston/models/RedditAPI/user/fetchUserOverview.swift
winston/models/User.swift
winston/views/UserView.swift

- Incorporates logic for infinite scrolling with a feed that is a mix of comments and posts
- Adds loader modifier logic to user profiles

add infinite scrolling to user profiles

---

winston/components/Media/mediaExtractor.swift
winston/views/SubredditPosts.swift

- fixes duplicate posts showing in the feed by filtering for post id's in a set for O(1) lookup time
- fixes assertion of 0th index in array that would crash when loading a feed

fix duplicate posts showing up in the feed

---

winston.xcodeproj/project.pbxproj

Changed Bundle Identifier to alpha.lo.cafe.winston

Changed Bundle Identifier to alpha.**

---

winston.xcodeproj/project.pbxproj

Forgot to change the app name for alpha version

---

winston.xcodeproj/project.pbxproj
winston/views/Settings/views/AboutPanel.swift

Changed Beta to Alpha in About Panel and changed version number to 0.1

---

winston/components/Links/PostLink.swift

Fixed duplicate share button

---

README.md

Updated the Subreddit in the README to the new one :)
#29

Update Subreddit in README.md

---

winston.xcodeproj/project.pbxproj

Alpha version 0.1

---

winston/components/Badge.swift
winston/components/LabeledSlider.swift
winston/components/Links/CommentLink/CommentLinkContent.swift
winston/components/Links/CommentLink/CommentLinkMore.swift
winston/components/Links/PostLink/PostLink.swift
winston/globals/defaultTheme.swift
winston/globals/defaults.swift
winston/globals/modelSamples/CommentSample.swift
winston/models/Comment.swift
winston/models/Message.swift
winston/models/RedditAPI/subs/fetchSubPosts.swift
winston/models/WinstonTheme/BadgeTheme.swift
winston/models/WinstonTheme/CommentsTheme.swift
winston/models/WinstonTheme/PostLinkTheme.swift
winston/views/PostView/PostReplies.swift
winston/views/PostView/PostView.swift
winston/views/Settings/views/BehaviorPanel.swift
winston/views/Settings/views/theming/editTypes/CommentsThemingPanel.swift
winston/views/Settings/views/theming/editTypes/postLink/CardSettings.swift
winston/views/Settings/views/theming/editing/BadgeSettings.swift
winston/views/SubredditPosts.swift

- Preferred search sort in settings
- Save sort per subreddit
- Save comment sort per post
- Support for themable user flairs
- Add theming for Load More button
- Add theming for unseen fade opacity

chore(Updates): Lots of small updates

---

winston.xcodeproj/project.pbxproj
winston/components/SubscribeButton.swift
winston/utils/exportImportSettings.swift
winston/views/Settings/views/GeneralPanel.swift

This PR adds two Buttons under Settings -> General that let you export all your settings (including posts box) as a json file. You can then import this file again to restore your settings

Add Settings Import and Export

---

winston/views/ChangeAuthAPIKey.swift
winston/views/Onboarding/Steps/Onboarding1OpeningSettings.swift
winston/views/Onboarding/Steps/Onboarding6Auth.swift

Fix `below's` to `below` in multiple files.

Fix grammar

---

winston/components/Links/CommentLink/CommentLinkContent.swift
winston/components/Links/PostLink/PostLinkNormal.swift
winston/components/Links/PostLink/getPostContentWidth.swift
winston/globals/defaultTheme.swift
winston/models/WinstonTheme/CommentsTheme.swift
winston/models/WinstonTheme/PostLinkTheme.swift
winston/models/WinstonTheme/PostTheme.swift
winston/views/PostView/PostContent.swift
winston/views/Settings/views/theming/editTypes/CommentsThemingPanel.swift
winston/views/Settings/views/theming/editTypes/post/PostTextsTheming.swift
winston/views/Settings/views/theming/editTypes/postLink/TextsSettings.swift

Adds the possibility to define line spacing. I personally find this useful when reading longer texts like WritingPrompts or HFY.

add line spacing

---

winston/components/Links/PostInBoxLink.swift
winston/components/Links/PostLink/FlairTag.swift
winston/components/Links/PostLink/SubsNStuffLine.swift
winston/components/Links/ShortPostLink.swift
winston/components/Markdownosaur.swift
winston/components/Media/mediaExtractor.swift
winston/components/SubredditIcon.swift
winston/components/SubredditPostsIOS.swift
winston/globals/defaults.swift
winston/models/Comment.swift
winston/models/Post.swift
winston/models/RedditAPI/shared/vote.swift
winston/models/Subreddit.swift
winston/views/PostView/PostContent.swift
winston/views/PostView/PostView.swift
winston/views/Settings/views/BehaviorPanel.swift

- Subreddit icons on all/home
- Quote text fixes
- Fixing comment likes

Various improvements

---

winston/globals/defaults.swift
winston/models/Subreddit.swift

little fix for broken subreddit search and code cleanup after performance merge

repair search for subreddits

---

winston.xcodeproj/project.pbxproj
winston/Tabber.swift
winston/models/RedditAPI/subs/fetchSubPosts.swift
winston/models/RedditAPI/user/fetchMe.swift
winston/models/RedditAPI/user/fetchUserOverview.swift
winston/models/Subreddit.swift
winston/utils/getItemId.swift
winston/views/MixedMediaFeedLinks.swift
winston/views/SubredditPosts.swift
winston/views/Subreddits/Subreddits.swift
winston/views/UserView.swift

- Enables saved posts
- Abstracts new view for multi media (mixed feed of posts and comments taken from UserView and made reusable)
- Expanded API implementation to support smart switching when subreddit is dedicated to saved posts
- Conditionally displays search bar and sorting (you cannot search nor can you sort saved posts)
- Fixes critical bug that prevented the user "me" object from populating when the app opened

Implement saved posts

---

winston/components/MD2.swift

Checks if URL starts with http/https

check URL scheme so internal URLs don't crash

---

winston/components/MD2.swift

Revert "check URL scheme so internal URLs don't crash"

---

winston/components/MD2.swift

Revert "Revert "check URL scheme so internal URLs don't crash""

---

winston/components/Badge.swift
winston/components/LightBoxImage/LightBoxOverlay.swift
winston/components/Links/CommentLink/CommentLink.swift
winston/components/Links/CommentLink/CommentLinkContent.swift
winston/components/Links/PostLink/PostLink.swift
winston/components/Links/PostLink/PostLinkCompact.swift
winston/components/Links/PostLink/PostLinkNormal.swift
winston/components/Modals/ReplyModal.swift
winston/globals/defaultTheme.swift
winston/models/Comment.swift
winston/models/Post.swift
winston/models/WinstonTheme/BadgeTheme.swift
winston/views/Settings/views/theming/editTypes/postLink/PostLinkThemingPanel.swift
winston/views/Settings/views/theming/editing/BadgeSettings.swift

Fix flairs and new comment indicators that were lost in rebase. Streamable videos are still bonked but too lazy to fix now

Fix user flairs and new comment indicators lost in rebase

---

winston/components/Links/PostLink/getPostContentWidth.swift
winston/components/Markdownosaur.swift
winston/utils/stringToAttr.swift

replaces REddit URLs in Markdown text for inline browsing, fixes nbsp in Markdown and fixes lost linespacing in Postlink view

replace Reddit URLs for inline browsing + small fixes

---

winston/components/Badge.swift
winston/components/Links/PostLink/PostLink.swift
winston/components/Links/PostLink/PostLinkCompact.swift
winston/components/Links/PostLink/PostLinkNormal.swift

- Overhauls logic for calculating post link sizing
- Fixes logic for displaying stuff in compact mode
- Fixes unseen dot/fade implementation
- Refactors some code

Fix compact mode

---

winston/components/Badge.swift
winston/components/Links/PostLink/PostLink.swift
winston/components/Links/PostLink/PostLinkCompact.swift
winston/components/Links/PostLink/PostLinkNormal.swift

Reverts lo-cafe/winston#271
We need to have fixed size for items, otherwise List will have to calculate each item's size on demand while you scroll, and that messes up with performance.

Revert "Fix compact mode"

---

winston/components/Links/PostLink/getPostContentWidth.swift
winston/components/Media/MediaPresenter.swift
winston/components/Media/mediaExtractor.swift
winston/models/Post.swift

This PR is built on top of https://github.com/lo-cafe/winston/pull/243. Merge that one first and I'll rebase this
Fixes streamable videos

Streamable videos

---

winston/components/SubredditPostsIPAD.swift
winston/models/Comment.swift
winston/models/Post.swift
winston/utils/openInBuiltInBrowser.swift
winston/views/MultiPostsView.swift

I made several QOL improvements for IPad, including Posts load on scroll and fitting width for PostView

several IPad related improvements

---

winston/views/MultiPostsView.swift
winston/views/SubredditPosts.swift

- can now fix itself if the feed fails to load but then loads successfully (bool will be reassigned)

better end of feed detection

---

winston/AppDelegate.swift
winston/components/Badge.swift
winston/components/Links/PostInBoxLink.swift
winston/components/Links/PostLink/PostLinkCompact.swift
winston/components/Links/PostLink/PostLinkNormal.swift
winston/components/Links/PostLink/getPostContentWidth.swift
winston/components/Media/MediaPresenter.swift
winston/components/Media/PreviewLink/PreviewLinkContent.swift
winston/components/Media/PreviewLink/PreviewModel.swift
winston/components/Media/RedditMediaPost.swift
winston/components/Media/VideoPlayerPost.swift
winston/components/Media/mediaExtractor.swift
winston/components/PostFloatingPill.swift
winston/globals/defaultTheme.swift
winston/globals/defaults.swift
winston/models/Post.swift
winston/models/WinstonTheme/PostLinkTheme.swift
winston/models/caches/BaseCache.swift
winston/models/caches/caches.swift
winston/utils/updatePostsInBox.swift
winston/views/PostView/PostReplies.swift
winston/views/PostView/PostView.swift
winston/views/Settings/views/theming/editTypes/postLink/CardSettings.swift

- Make divider optional in themes
- Make link/repost background slightly more visible
- Fixes for saving seen comments and making sure they update the UI correctly

Lots of small fixes

---

winston/components/Links/PostLink/PostLinkCompact.swift
winston/components/Links/PostLink/PostLinkNormal.swift
winston/globals/defaults.swift
winston/views/Settings/views/BehaviorPanel.swift

- adds a posts behavior option to disable opening the media from the feed. instead, it would open the post page.

Add option to disable opening media from the feed

---

winston/components/Media/VideoPlayerPost.swift
winston/globals/defaults.swift
winston/views/Settings/views/BehaviorPanel.swift

option to mute videos on fullscreen and stop playback on leave when autoplay=false
closes: #232

option to mute videos + stop playback on leave fullscreen

---

winston/models/Comment.swift
winston/models/Post.swift
winston/models/RedditAPI/shared/vote.swift

Fix voting

---

winston/components/Media/VideoPlayerPost.swift
winston/components/SubredditPostsIOS.swift
winston/globals/defaults.swift
winston/views/Settings/views/BehaviorPanel.swift
winston/views/SubredditPosts.swift

Add behavior toggle for audio changes, reset home/all/popular filters on new fetch, and fix for compact mode.

---

winston/components/FilterButton.swift
winston/components/FloatingFeedMenu/FloatingFeedMenu.swift
winston/components/SubredditPostsIPAD.swift
winston/views/MultiPostsView.swift
winston/views/SubredditPosts.swift
winston/views/Subreddits/SubredditsStack.swift

This PR fixes a few IPad related problems including the width reset issue with the Waterfall component. It also adds the new floatingMenu Button on IPad Subreddit View

various IPad fixes

---

winston/Navigation/Nav.swift

This hopefully finally fixes the nav problems introduced by my last fix for reddit links.

fix tab navpath reset

---

winston/components/Markdown Handling/External to Internal Links.swift
winston/components/SubredditPostsIPAD.swift

small fixes to the position of the floatingmenu on IPad and regex url recognition

IPad layout + Link regex fix

---

winston/components/Media/VideoPlayerPost.swift

Add a one line fix that resets the audiosession on video disappear

 reset audiosession on video disappear @Frostplexx

---

winston/components/Media/PreviewLink/PreviewModel.swift
winston/views/PostView/PostContent.swift

spoiler handling in selftext + escape link preview

spoiler handling in selftext + escape link preview
